version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-debugging"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ggy10f8x00qa"
s3_prefix = "sam-debugging"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
